### ISSUE TITLE
Do not create new trials when metadata gets merged 

### ISSUE THREAD

**Issue by curlup** [CIMAC-CIDC/cidc-api-gae#45]
as it does here

https://github.com/CIMAC-CIDC/cidc-api-gae/blob/b87aaecae9308d5e1bc9ea78e7ebc896ded83d79/cidc_api/models.py#L271-L276

also may be add a safeguard that a new trial might be created only through the admin interface.

**Comment by jacoblurye** [comment]
https://github.com/CIMAC-CIDC/cidc-api-gae/pull/59
